name: Artifacts

on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
  push:
    tags:
      - '*'
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:

  m1-build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
            # grab the commit passed in via `tag`, if any
            ref: ${{ github.event.inputs.tag }}
            # need to fetch unshallow so that setuptools_scm can infer the version
            fetch-depth: 0

      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Build artifact
        id: build
        with:
          arch: aarch64
          distro: bullseye
          githubToken: ${{ github.token }} # Not required, but speeds up builds
          #dockerRunArgs: |
          #  --workdir "/work" --volume "${PWD}/dist:/work/dist"
          install: |
            apt-get update -qq -y
            # python3 == 3.8 on ubuntu 20.04
            apt-get -qq install -y python-is-python3 python3 python3-pip git
          run: >-
            pip install . &&
            pip install pyinstaller &&
            make freeze &&
            mv dist/ /dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist/vyper.*


  unix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
        with:
            # grab the commit passed in via `tag`, if any
            ref: ${{ github.event.inputs.tag }}
            # need to fetch unshallow so that setuptools_scm can infer the version
            fetch-depth: 0

      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Generate Binary
        run: >-
          pip install . &&
          pip install pyinstaller &&
          make freeze

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist/vyper.*


  macos-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
            # grab the commit passed in via `tag`, if any
            ref: ${{ github.event.inputs.tag }}
            # need to fetch unshallow so that setuptools_scm can infer the version
            fetch-depth: 0

      - name: Generate Binary
        run: |
          wget "https://www.python.org/ftp/python/3.9.10/python-3.9.10-macos11.pkg"
          installer -pkg python-3.9.10-macos11.pkg -target /
          python -m ensurepip --upgrade
          pip install .
          pip install pyinstaller
          make freeze

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist/vyper.*


  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
            # grab the commit passed in via `tag`, if any
            ref: ${{ github.event.inputs.tag }}
            # need to fetch unshallow so that setuptools_scm can infer the version
            fetch-depth: 0

      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Generate Binary
        run: >-
          pip install . &&
          pip install pyinstaller &&
          ./make.cmd freeze

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: dist/vyper.*
